apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lvn-app
  namespace: u-1
spec:
  ingressClassName: nginx
  rules:
    - host: lvn.u-1.csc8567.luxbulb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lvn-app
                port:
                  number: 80
