apiVersion: v1
kind: Secret
metadata:
  name: lvn-secrets
  namespace: u-1
type: Opaque
stringData:
  POSTGRES_DB: lvn
  POSTGRES_USER: lvn
  POSTGRES_PASSWORD: change-me
  SECRET_KEY: change-me
  DATABASE_URL: postgresql+psycopg://lvn:change-me@lvn-postgres:5432/lvn
